Models/ErrorViewModel.cs
namespace TestImages.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Images.cs
using System.ComponentModel.DataAnnotations;

namespace TestImages.Models
{
    public class Images
    {
        [Key]
        public int Id { get; set; }
        public string? Title { get; set; }
        public string? Descrption { get; set; }

        [Required(ErrorMessage ="الرجاء قم باختيار ملف ")]
        public string? ImageUrl { get; set; }

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TestImages.Models;

namespace TestImages.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ImagesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TestImages.Data;
using TestImages.Models;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace TestImages.Controllers
{
    public class ImagesController : Controller
    {
        private readonly TestImagesDbContext _context;

        public ImagesController(TestImagesDbContext context)
        {
            _context = context;
        }
        // GET: ImagesController
        public ActionResult Index()
        {
           
            return View(_context.Image.ToList());
        }

        // GET: ImagesController/Details/5
        public ActionResult Details(int id)
        {
            return View(_context.Image.FirstOrDefault(d=>d.Id==id));
        }

        // GET: ImagesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ImagesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Images images)
        {
            try
            {
                //هنايتم اخذ الصورة
                var file = HttpContext.Request.Form.Files;
                //يتم الفحص اذا وجد صورة
                if (file.Count() > 0)
                {
                    //هنا يتم اخذ اسم الصورة مع الامتداد ويتم اضافة رقم عشوائي للاسم عشان تكرر الصور

                    //دالة لتوليد رقم لا يحتوي على علامة (.)
                    //Guid.NewGuid() يولد رقم عشوائي

                    Guid newGuid = RemoveDotFromGuid(Guid.NewGuid());

                    string ImageName = newGuid.ToString() + Path.GetExtension(file[0].FileName);
                   
                    //هنا يتم قرائة امتداد الملف الذي بنخزن فية الصورة
                    var fileStream = new FileStream(Path.Combine(@"wwwroot/Images/", ImageName), FileMode.Create);
                   
                    //هنا نسخنا الصورة للملف 
                    file[0].CopyTo(fileStream);
                  
                    //هنا بنسند الاسم الجديد الذي كوناه طالع
                    images.ImageUrl = ImageName;
                }
               
                _context.Image.Add(images);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ImagesController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ImagesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ImagesController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ImagesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        public static Guid RemoveDotFromGuid(Guid guid)
        {
            string guidString = guid.ToString();
            string newGuidString = guidString.Replace(".", "");
            Guid newGuid = new Guid(newGuidString);
            return newGuid;
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Images/Create.cshtml
@model TestImages.Models.Images

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Authors</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Images" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="Descrption" class="control-label"></label>
                <input asp-for="Descrption" class="form-control" />
                <span asp-validation-for="Descrption" class="text-danger"></span>
            </div>
     
             <div class="form-group">
                   <div class="form-group">
                        <span class="text-danger invisible" id="ImageError">Please choose image</span>
                    </div>
                            <label asp-for="ImageUrl" class="control-lable"></label>
                            <input type="file" class="form-control" asp-for="ImageUrl" id="userImage" onchange="handleFile()"/>
                             <span asp-validation-for="ImageUrl" class="text-danger"></span>
                        </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");} 


  @*  للتحقق من حجم الصورة مع الامتداد الذي تشتي تحددة*@
    <script>
        
    function handleFile() {
      $("#ImageError").addClass("invisible").removeClass("visible");

     var inputElement = document.getElementById("userImage");
    var file = inputElement.files[0]; // الحصول على الملف المحدد
    var fileSize = file.size;
    var fileName = inputElement.value.split("\\").pop(); // تصحيح طريقة الحصول على اسم الملف
    var fileExt = fileName.split(".").pop(); // الحصول على امتداد الملف

      var error = IsImageValid(fileSize, fileExt);
      if (error !== "") {
        $("#ImageError").text(error).removeClass("invisible").addClass("visible");
         inputElement.value = ""; // إعادة تعيين قيمة الملف المحدد
        return;
      }

      // استمر في المعالجة الأخرى للصورة
    }

    //دالة التحقق من الحجم مع الامتداد 
    function IsImageValid(fileSize, fileExt) {
      var error = "";
      error = IsExtensionValid(fileExt);

      if (error !== "") {
        return error;
      }

      error = IsFileSizeValid(fileSize);
      if (error !== "") {
        return error;
      }

      return "";
    }

    //دالة التحقق من الامتداد المطلوب يمكنك الاضافة امتدادات اخرى 
    function IsExtensionValid(fileExt) {
      var allowedExtensions = ["jpg", "png","pdf"];
      if (!allowedExtensions.includes(fileExt)) {
          //الرسالة في حالة الخطأ
        return "Only Jpeg or Png or pdf files are Accepted";
      }

      return "";
    }

    //دالة التحقق من حجم الملف 
    function IsFileSizeValid(fileSize) {
      var maxSizeInBytes = 100 * 1024; // 100 KB
      var fileSizeInBytes = Math.round(fileSize);

      if (fileSizeInBytes > maxSizeInBytes) {
          //رسالة خطأ في الحجم
        return "Files Sized over 100 KB are not Allowed";
      }

      return "";
    }

    function IsImageSelected() {
      if ($("#userImage").val() === "Error") {
        return "Image Not Selected To Upload";
      }

      return "";
    }

    function ValidateForm() {
      var error = IsImageSelected();
      if (error !== "") {
        $("#ImageError").text(error).removeClass("invisible").addClass("visible");
        return false;
      }

      return true;
    }
    </script>
}

Views/Images/Index.cshtml
@model IEnumerable<TestImages.Models.Images>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<table id="basic-datatable" class="dt-dataTables-data table dt-responsive table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descrption)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageUrl)
            </th>
          
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
             <td>
                @Html.DisplayFor(modelItem => item.Descrption)
            </td>
            
           <td>
     @*   pdf هنا يتم اخذ امتداد الملف لمعرفة انه صورة او *@
    @{

        string text = item.ImageUrl;
        int dotIndex = text.IndexOf('.');
        string extractedText = dotIndex >= 0 && dotIndex < text.Length - 1 ? text.Substring(dotIndex + 1) : string.Empty;
    }
      @*  ياخذ الصورة الافتراضية لايقونة البي دي اف pdf هنا فحص  الامتداد اذا كان  *@
    @if (extractedText == "pdf")
    {
        <a href="~/Images/@item.ImageUrl" download>
            <img src="~/Images/pdf.png" style="width:50px; height:50px" alt="PDF Image" />
        </a>
    }
    else if (IsImageFile(extractedText))
    {
        <a href="~/Images/@item.ImageUrl" download>
            <img src="~/Images/@item.ImageUrl" style="width:50px; height:50px" alt="Image" />
        </a>
    }
    else
    {
        <p>الملف غير معروف</p>
    }

</td>
          
        </tr>
}
    </tbody>

</table>


@functions {
    public bool IsImageFile(string fileExtension)
    {
        string[] imageExtensions = { "jpg", "jpeg", "png", "gif" };
        return imageExtensions.Contains(fileExtension.ToLower());
    }
}

	
	<script src="https://code.jquery.com/jquery-3.7.0.js"></script> 
	<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script> 
	<script src="https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js"></script> 
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script> 
	<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script> 
	<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script> 
	<script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js"></script> 
	


	<script>
		$('.dt-dataTables-data').dataTable({
                     dom: 'Bfrtip',
        buttons: [
            'copyHtml5',
            'excelHtml5',
            'csvHtml5',
            'pdfHtml5'
        ]

        });	 
		
	</script>	

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestImages</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestImages.styles.css" asp-append-version="true" />

	<link href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" rel="stylesheet"> 
	<link href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css" rel="stylesheet"> 
	

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestImages</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Images" asp-action="Index">الصور</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TestImages - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>